#!/usr/bin/env python

import sys

import transsys


f = open('mhcells.trl', 'r')
p = transsys.TranssysProgramParser(f)
tp = p.parse_transsys()
lsys = p.lsys_lines(f)
print str(tp)
transsys.write_lsys_code(sys.stdout, lsys)
sys.exit()

ti = transsys.TranssysInstance(tp)
ts = ti.time_series(100)
for i in xrange(len(ts)) :
  ts[i].write_gnuplot(sys.stdout, i)
