#!/usr/bin/env python

# $Id$
# $Revision$
# $Author$
# $Date$

import sys
import getopt
import types
import os
import popen2
import copy
import random
import string
import math
import re

import transsys
# import transsys.clib
import transdecode
import transsys.optim


def read_lsysopt_framework(f) :
  p = transsys.TranssysProgramParser(f)
  transsys_program = p.parse()
  if not isinstance(transsys_program, transsys.TranssysProgram) :
    raise StandardError, 'bad trl file: first item is not a transsys program'
  lsys_program = p.parse()
  if not isinstance(lsys_program, transsys.LsysProgram) :
    raise StandardError, 'bad trl file: second item is not an lsys'
  return transsys_program, lsys_program


def write_transopt_comments(f, tp_opt, obj_opt, opt_descriptor) :
  tp_opt.comments.extend(obj_opt.getTranssysProgramComments())
  f.write('// transsys %s: objective: %g (%s)\n' % (tp_opt.name, obj_opt.fitness, opt_descriptor))
  f.write(str(tp_opt))
  f.flush()


def write_lsysopt_combination(basename, tp_index, restart_index, lsys_frame, transsys_frame, transsys_program) :
  f = open('%s_%03d_%03d.trl' % (basename, tp_index, restart_index), 'w')
  lsys = copy.deepcopy(lsys_frame)
  lsys.dissociate_transsys()
  tp = copy.deepcopy(transsys_frame)
  tp.merge(transsys_program)
  lsys.associate_transsys(tp)
  f.write(str(tp))
  f.write(str(lsys))
  f.close()


def optimise_ontogenesis(lsys_frame, transsys_frame, num_timesteps, transsys_program, disparity_function_list, optimiser, logfile = None) :
  current_tp = copy.deepcopy(transsys_program)
  header = True
  for timestep in xrange(num_timesteps) :
    disparity_number = 0
    for disparity_function in disparity_function_list :
      objective_function = transsys.optim.LsysObjectiveFunction(lsys_frame, transsys_frame, disparity_function, timestep)
      optResult = optimiser.optimise(current_tp, objective_function)
      if logfile is not None :
        optResult.write_log(logfile, '%d %d' % (timestep, disparity_number), header, 'tp_index restart_index')
        header = False
      disparity_number = disparity_number + 1
  return optResult


def usage() :
  print 'command line options:'
  print '-n <int>: specify number of time steps (derivations)'
  print '-r <int>: specify number of random restarts'
  print '-s <int>: specify random seed'
  print '-f <lsysfile>: specify lsys framework'
  print '-o [stddev | overlap | diffsign]: set objective function'
  print '-P <optspecfile>: specify file with optimiser specification'
  print '-T <transformerspecfile>: specify file with parameter transformer specification'
  print '-L <logfile>: specify optimisation log file'
  print '-c <lsysoutbase>: specify base name for lsys output files,'
  print '    suffixed by _t<transsysnum>_r<restartnum>.trl'
  print '-v: verbose'
  print '-h: print this help and exit'


num_timesteps = 0
rndseed = 1
num_restarts = 0
frameworkfile_name = None
eliminateFlatComponents = False
delta = None
improvement_threshold = 0.0
disparity_function = None
verbose = 0
optimiserfile_name = None
transformerfile_name = None
lsysoutfile_base = None
logfile_name = None
options, args = getopt.getopt(sys.argv[1:], '-f:o:n:s:L:P:T:r:c:vh')
for opt, par in options :
  if opt == '-h' :
    usage()
    sys.exit()
  elif opt == '-f' :
    frameworkfile_name = par
  elif opt == '-o' :
    if par == 'stddev' :
      disparity_function = transsys.optim.stddev_disparity
    elif par == 'overlap' :
      disparity_function = transsys.optim.overlap_disparity
    elif par == 'diffsign' :
      disparity_function = transsys.optim.difference_sign_disparity
    else :
      raise StandardError, 'objective function "%s" not recognised' % par
  elif opt == '-n' :
    num_timesteps = int(par)
  elif opt == '-s' :
    rndseed = int(par)
  elif opt == '-L' :
    logfile_name = par
  elif opt == '-c' :
    lsysoutfile_base = par
  elif opt == '-P' :
    optimiserfile_name = par
  elif opt == '-T' :
    transformerfile_name = par
  elif opt == '-r' :
    num_restarts = int(par)
  elif opt == '-v' :
    verbose = 1
    # transsys.clib.setverbose(0)
  else :
    raise StandardError, 'unknown option "%s"' % opt
if frameworkfile_name is None :
  raise StandardError, 'no framework lsysfile specified'
if optimiserfile_name is None and num_restarts > 0 :
  raise StandardError, 'no optimiser file given but %d restarts requested' % num_restarts
if optimiserfile_name is None and logfile_name is not None :
    raise StandardError, 'no optimiser file given but optimisation logfile "%s" requested' % logfile_name
f = open(frameworkfile_name, 'r')
transsys_frame, lsys_frame = read_lsysopt_framework(f)
f.close()
if optimiserfile_name is None :
  optimiser = None
else :
  f = open(optimiserfile_name, 'r')
  optimiser = transsys.optim.parse_optimiser(f)
  f.close()
  optimiser.verbose = verbose
  if transformerfile_name is not None :
    f = open(transformerfile_name, 'r')
    optimiser.transformer = transsys.optim.parse_parameter_transformer(f)
    f.close()
if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout
objective_function = transsys.optim.LsysObjectiveFunction(lsys_frame, transsys_frame, disparity_function, num_timesteps)
# print str(optimiser)
p = transsys.TranssysProgramParser(infile)
outfile.write('// cmdline: %s\n' % ' '.join(sys.argv))
if logfile_name is not None :
  logfile = open(logfile_name, 'w')
else :
  logfile = None
transsys_program = p.parse()
tp_index = 0
while transsys_program is not None :
  if num_restarts == 0 :
    if optimiser is None :
      tp_opt = transsys_program
      obj_opt = objective_function(tp_opt)
      write_transopt_comments(outfile, transsys_program, obj_opt, 'evaluated')
    else :
      optResult = optimiser.optimise(transsys_program, objective_function)
      tp_opt = optResult.optimised_transsys_program
      write_transopt_comments(outfile, tp_opt, optResult.objectiveOptimum, 'optimised, original')
      if logfile is not None :
        optResult.write_log(logfile, '%d' % tp_index, tp_index == 0, 'tp_index')
        logfile.flush()
    if lsysoutfile_base is not None :
      write_lsysopt_combination(lsysoutfile_base, tp_index, 0, lsys_frame, transsys_frame, tp_opt)
  else :
    optimiser.randomInitRange = 1.0
    for restart_index in xrange(num_restarts) :
      optResult = optimiser.optimise(transsys_program, objective_function)
      tp_opt = optResult.optimised_transsys_program
      write_transopt_comments(outfile, tp_opt, optResult.objectiveOptimum, 'optimised, restart %d' % restart_index)
      if logfile is not None :
        optResult.write_log(logfile, '%d %d' % (tp_index, restart_index), tp_index == 0 and restart_index == 0, 'tp_index restart_index')
        logfile.flush()
      if lsysoutfile_base is not None :
        write_lsysopt_combination(lsysoutfile_base, tp_index, restart_index, lsys_frame, transsys_frame, tp_opt)
  outfile.write('\n')
  transsys_program = p.parse()
  tp_index = tp_index + 1
