#!/bin/sh

# script to test whether running the python scripts results in an
# exit code of 0 (indicating success). These tests are intended to
# pick up changes in the python modules require changes in the scripts
# etc.; they are not intended as a thorough test of the scripts.

# $Id$
# $Revision$
# $Author$
# $Date$


function runcmd ()
{
  cmd=$*
  echo $cmd
  if $cmd ; then
    true
  else
    echo exit $?
    exit 1
  fi
}


runcmd ./transopt_sa -f squaresum -P transopt_sa_test_saspec.txt -x transopt_sa_test_obj.txt -r 1 -L transopt_sa_test_out.dat transopt_sa_test.tra transopt_sa_test_out.tra
