#!/usr/bin/env python

import sys
import transsys


p = transsys.TranssysProgramParser(open(sys.argv[1], 'r'))
tp = p.parse_transsys()
for gene in tp.gene_list :
  print gene.name
  rf = gene.regulating_factors()
  for f in rf :
    print '  %s' % f.name
  print
for factor in tp.factor_list :
  print factor.name
  rg = tp.regulated_genes(factor)
  for g in rg :
    print '  %s' % g.name

