#!/usr/bin/env python

import sys
import getopt

import transsys
import transsys.clib


def compare_time_series(ts1, ts2) :
  if len(ts1) != len(ts2) :
    print 'time series lengths differ: %d != %d' % (len(ts1), len(ts2))
  for i in xrange(len(ts1)) :
    if ts1[i].transsys_program is not ts2[i].transsys_program :
      print 'transsys mismatch: %s != %s' % (ts1[i].transsys.name, ts2[i].transsys.name)
    for j in xrange(len(ts1[i].factor_concentration)) :
      print '%f' % (ts1[i].factor_concentration[j] - ts2[i].factor_concentration[j]),
    print



options, args = getopt.getopt(sys.argv[1:], 'h')
for opt, arg in options :
  if opt == '-h' :
    print 'help...'
  else :
    raise StandardError, 'unknown option "%s"' % opt
if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1])
else :
  outfile = sys.stdout

parser = transsys.TranssysProgramParser(infile)
tp = parser.parse()
ti = transsys.TranssysInstance(tp)
for i in xrange(len(ti.factor_concentration)) :
  ti.factor_concentration[i] = float(i);
nsteps = 500
sp = 1
print str(ti)
print
print '-' * 60
x = ti.time_series(nsteps, sp)
print '-' * 60
for t in x :
  print t
ts = ti.time_series_old(nsteps, sp)
compare_time_series(x, ts)
